/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peymentsystem1;

/**
 *
 * @author Lenovo
 */
public class Bills_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Bills_Interface
     */
    public Bills_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BILLS_LABEL = new javax.swing.JLabel();
        Electricity_Button = new javax.swing.JButton();
        Water_Button = new javax.swing.JButton();
        School_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BILLS_LABEL.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        BILLS_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BILLS_LABEL.setText("Pay Bills");

        Electricity_Button.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        Electricity_Button.setText("Electricty");
        Electricity_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Electricity_ButtonActionPerformed(evt);
            }
        });

        Water_Button.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        Water_Button.setText("School");
        Water_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Water_ButtonActionPerformed(evt);
            }
        });

        School_Button.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        School_Button.setText("Water");
        School_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BILLS_LABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 168, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Water_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(School_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Electricity_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BILLS_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(School_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Water_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Electricity_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Electricity_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Electricity_ButtonActionPerformed
        // TODO add your handling code here:
        Bills_Interface_Electricity02 Electricity02 = new Bills_Interface_Electricity02();
        Electricity02.setVisible(true);
    }//GEN-LAST:event_Electricity_ButtonActionPerformed

    private void School_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_ButtonActionPerformed
        // TODO add your handling code here:
        Bills_Interface_Water02 Water02 = new Bills_Interface_Water02();
        Water02.setVisible(true);
    }//GEN-LAST:event_School_ButtonActionPerformed

    private void Water_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Water_ButtonActionPerformed
        // TODO add your handling code here:
        Bills_Interface_School02 School02 = new Bills_Interface_School02();
        School02.setVisible(true);
    }//GEN-LAST:event_Water_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bills_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bills_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bills_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bills_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bills_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BILLS_LABEL;
    private javax.swing.JButton Electricity_Button;
    private javax.swing.JButton School_Button;
    private javax.swing.JButton Water_Button;
    // End of variables declaration//GEN-END:variables
}
