/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peymentsystem1;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class BuyLoad_BPI_Interface0001 extends javax.swing.JFrame {

    /**
     * Creates new form BuyLoad_BPI_Interface0001
     */
    public BuyLoad_BPI_Interface0001() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPI_Account_Title = new javax.swing.JLabel();
        BPI_AccountNo_Title = new javax.swing.JLabel();
        BPI_AccountNo_Text = new javax.swing.JTextField();
        BPI_Pay_Button = new javax.swing.JButton();
        ONLINE_BANK_BPI_LABEL = new javax.swing.JLabel();
        BPI_Amount_Text = new javax.swing.JTextField();
        BPI_Amount_Title = new javax.swing.JLabel();
        BPI_Account_Text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BPI_Account_Title.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        BPI_Account_Title.setText("Account Name");

        BPI_AccountNo_Title.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        BPI_AccountNo_Title.setText("Account No.");

        BPI_Pay_Button.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        BPI_Pay_Button.setText("PAY");
        BPI_Pay_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPI_Pay_ButtonActionPerformed(evt);
            }
        });

        ONLINE_BANK_BPI_LABEL.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        ONLINE_BANK_BPI_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ONLINE_BANK_BPI_LABEL.setText("Buy from BPI Load");

        BPI_Amount_Title.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        BPI_Amount_Title.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ONLINE_BANK_BPI_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BPI_AccountNo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPI_AccountNo_Title)
                            .addComponent(BPI_Account_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPI_Amount_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPI_Amount_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPI_Account_Title)
                            .addComponent(BPI_Pay_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ONLINE_BANK_BPI_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPI_Amount_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPI_Amount_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPI_Account_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPI_Account_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPI_AccountNo_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPI_AccountNo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BPI_Pay_Button)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPI_Pay_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPI_Pay_ButtonActionPerformed
        // TODO add your handling code here:
                String Amt = BPI_Amount_Text.getText();
                String Acc = BPI_Account_Text.getText();
                String Email = BPI_AccountNo_Text.getText();
                
                try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/payment_finals", "root", "")) 
                {
                    System.out.println(connection);
            // Prepare the SQL statement
            String sql = "INSERT INTO buy_and_pay (Amount, Account_name, Account_number) VALUES (?, ?, ?)";
                                                                                                  
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, Amt);
            statement.setString(2, Acc);
            statement.setString(3, Email);
            
            // Execute the query
                    int resultSet = statement.executeUpdate();
                    int rowsAffected = resultSet;
                    
            
            // Check if the login is successful
            if (rowsAffected > 0) 
            {
                JOptionPane.showMessageDialog(null, "Payment successful!");
                System.out.println(rowsAffected);
                Payment_main_UI Main_menu = new Payment_main_UI();
                Main_menu.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Payment Failure");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e + "Database Connection Error" + e.getMessage());
        }
    }//GEN-LAST:event_BPI_Pay_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyLoad_BPI_Interface0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyLoad_BPI_Interface0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyLoad_BPI_Interface0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyLoad_BPI_Interface0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyLoad_BPI_Interface0001().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPI_AccountNo_Text;
    private javax.swing.JLabel BPI_AccountNo_Title;
    private javax.swing.JTextField BPI_Account_Text;
    private javax.swing.JLabel BPI_Account_Title;
    private javax.swing.JTextField BPI_Amount_Text;
    private javax.swing.JLabel BPI_Amount_Title;
    private javax.swing.JButton BPI_Pay_Button;
    private javax.swing.JLabel ONLINE_BANK_BPI_LABEL;
    // End of variables declaration//GEN-END:variables
}
