/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peymentsystem1;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class SendLoad_Interface extends javax.swing.JFrame {

    /**
     * Creates new form SendLoad_Interface01
     */
    public SendLoad_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Send_Load_Title = new javax.swing.JLabel();
        Send_Text_Title = new javax.swing.JLabel();
        Amount_Text_Title = new javax.swing.JLabel();
        Send_Button = new javax.swing.JToggleButton();
        Send_Text_Field = new javax.swing.JTextField();
        Amount_Text_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Send_Load_Title.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        Send_Load_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Send_Load_Title.setText("Send Money");

        Send_Text_Title.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        Send_Text_Title.setText("Send To:");

        Amount_Text_Title.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        Amount_Text_Title.setText("Amount:");

        Send_Button.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        Send_Button.setText("Send");
        Send_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_ButtonActionPerformed(evt);
            }
        });

        Send_Text_Field.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        Send_Text_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_Text_FieldActionPerformed(evt);
            }
        });

        Amount_Text_Field.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Send_Load_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Send_Text_Title)
                        .addGap(18, 18, 18)
                        .addComponent(Send_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Amount_Text_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Amount_Text_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(Send_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Send_Load_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Send_Text_Field)
                    .addComponent(Send_Text_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amount_Text_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(Send_Button)
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Send_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Send_Text_FieldActionPerformed

    private void Send_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_ButtonActionPerformed
        // TODO add your handling code here:
                String Amt = Amount_Text_Field.getText();
                double Amt2 = Double.parseDouble(Amt) * -1;
                String Acc = Send_Text_Field.getText();
                String AccNo = Send_Load_Title.getText();
                
                try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/payment_finals", "root", "")) 
                {
                    System.out.println(connection);
            // Prepare the SQL statement
            String sql = "INSERT INTO buy_and_pay (Amount, Account_number, Account_name) VALUES (?, ?, 0)";
                                                                                                  
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setDouble(1, Amt2);
            statement.setString(2, Acc);
            statement.setString(3, AccNo);
            
            // Execute the query
                    int resultSet = statement.executeUpdate();
                    int rowsAffected = resultSet;
                    
            
            // Check if the login is successful
            if (rowsAffected > 0) 
            {
                JOptionPane.showMessageDialog(null, "Payment successful!");
                System.out.println(rowsAffected);
                Payment_main_UI Main_menu = new Payment_main_UI();
                Main_menu.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Payment Failure");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e + "Database Connection Error" + e.getMessage());
        }
    }//GEN-LAST:event_Send_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendLoad_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendLoad_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendLoad_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendLoad_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendLoad_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount_Text_Field;
    private javax.swing.JLabel Amount_Text_Title;
    private javax.swing.JToggleButton Send_Button;
    private javax.swing.JLabel Send_Load_Title;
    private javax.swing.JTextField Send_Text_Field;
    private javax.swing.JLabel Send_Text_Title;
    // End of variables declaration//GEN-END:variables
}
